name: CI Dispatch

on:
  workflow_dispatch:
    inputs:
      sming_repo:
        description: 'Full URL for Sming repository'
        default: 'https://github.com/mikee47/Sming'
        type: string
      sming_branch:
        description: 'Sming branch to run against'
        default: 'develop'
        type: string

jobs:
  build:
    uses: mikee47/Sming/.github/workflows/library.yml@fix/ccache-library
    with:
      sming_repo: ${{ inputs.sming_repo }}
      sming_branch: ${{ inputs.sming_branch }}
